### ISSUE TITLE
Found a good use case

### ISSUE THREAD

**Issue by samegavi** [ekzhang/inline-sql#2]
I was excited by this project which made me think a lot about programming language design. Even though this may not be the intention for creating it as its probably only an experiment I found a good use case for it based on a "getting started with SQL in Google Colab " I used sometime ago.

**Comment by ekzhang** [comment]
Awesome, thanks for sharing this Samuel! Really happy to see that you like the library and are using it on a quick CSV workflow to analyze some COVID data. :D
